/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EmuladorEcran.java
 *
 * Created on 19/Abr/2012, 19:48:01
 */
package poweremulator;


import com.sun.xml.internal.ws.api.server.Module;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;
import reflection.GeneticLoader;

/**
 *
 * @author Miranda
 */
public class EmuladorEcran extends javax.swing.JFrame {
    
    
    private GeneticLoader loader;
    
    
    String caminho;
    String URL;
    Boolean URLSite=true;
    ArrayList peso = new ArrayList();
    ArrayList valor = new ArrayList();
    String msg;
    /** Creates new form EmuladorEcran */
    public EmuladorEcran() {
        initComponents();
        
        loader = new GeneticLoader();

        loadData(this.ProblemList,loader.getAlgorithms());
        loadData(this.MutationList,loader.getMutation());
        loadData(this.SelectionList,loader.getSelections());
        loadData(this.ReplacementList,loader.getReplacements());
        loadData(this.RecombinationList,loader.getRecombinations());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        TabMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        Modulos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Text_Caminho = new javax.swing.JTextField();
        Carregar = new javax.swing.JButton();
        Executar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        OneMax_Name = new javax.swing.JTextField();
        OneMax_ProblemID = new javax.swing.JTextField();
        OneMax_Population = new javax.swing.JTextField();
        OneMax_Alello = new javax.swing.JTextField();
        OneMax_BestFitness = new javax.swing.JTextField();
        OneMax_Iteracoes = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        OneMax_ClientID = new javax.swing.JTextField();
        OneMax_Carregar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        Text_SelectionValor = new javax.swing.JTextField();
        ComboBox_Selection = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ComboBox_mutation = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        Text_MutationValor = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ComboBox_recombination = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        ComboBox_replacement = new javax.swing.JComboBox();
        Text_Recombination_1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Text_Recombination_2 = new javax.swing.JTextField();
        Text_SelectionValor_2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        KnapSack_Name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        KnapSack_ProblemID = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        KnapSack_ClientID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        KnapSack_Population = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        KnapSack_BestFitness = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        KnapSack_Iteracoes = new javax.swing.JTextField();
        KnapSack_Gerar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        KnapSack_NumItems = new javax.swing.JLabel();
        KnapSack_Penalty = new javax.swing.JLabel();
        KnapSack_MaxWeight = new javax.swing.JTextField();
        KnapSack_Allelo = new javax.swing.JTextField();
        KnapSack_PenaltY = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        KnapSack_Peso = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        KnapSack_Valor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        KnapSack_Monitor = new javax.swing.JTextArea();
        KnapSack_Adicionar = new javax.swing.JButton();
        ComboBox_Selection_KnapSack = new javax.swing.JComboBox();
        ComboBox_Mutation_KnapSack = new javax.swing.JComboBox();
        ComboBox_Recombination_KnapSack = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        Text_Replacement_1 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        Text_Replacement_2 = new javax.swing.JTextField();
        ComboBox_replacement_KnapSack = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        Text_Mutation_KnapSack = new javax.swing.JTextField();
        Text_SelectionValor_KnapSack = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        KnapSack_Lenght = new javax.swing.JTextField();
        KnapSack_Mode = new javax.swing.JTextField();
        Text_SelectionValor_KnapSack2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProblemList = new javax.swing.JList();
        jLabel24 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtProblem = new javax.swing.JTextArea();
        jLabel45 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        SelectionList = new javax.swing.JList();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtSelection = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        RecombinationList = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtRecombination = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        MutationList = new javax.swing.JList();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtMutation = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ReplacementList = new javax.swing.JList();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtReplacement = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setText("PowerEmulator");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        TextArea.setBackground(new java.awt.Color(0, 0, 0));
        TextArea.setColumns(20);
        TextArea.setEditable(false);
        TextArea.setFont(new java.awt.Font("Courier New", 0, 12));
        TextArea.setForeground(new java.awt.Color(51, 255, 0));
        TextArea.setRows(5);
        TextArea.setAutoscrolls(false);
        jScrollPane1.setViewportView(TextArea);

        Modulos.setText("Carregar Modulos");
        Modulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModulosActionPerformed(evt);
            }
        });

        jLabel1.setText("Caminho");

        Text_Caminho.setText("http://code.dei.estt.ipt.pt:81/loader/load4.txt");
        Text_Caminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_CaminhoActionPerformed(evt);
            }
        });

        Carregar.setText("Carregar");
        Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarActionPerformed(evt);
            }
        });

        Executar.setText("Executar");
        Executar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExecutarActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Text_Caminho, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Executar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Modulos)
                .addContainerGap(679, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Modulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Text_Caminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carregar)
                    .addComponent(Executar)
                    .addComponent(Limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
        );

        TabMain.addTab("Monitor", jPanel1);

        jLabel3.setText("Problem Name:");

        jLabel4.setText("ProblemID:");

        jLabel5.setText("Population size:");

        jLabel6.setText("Alello size:");

        jLabel7.setText("Param Best fitness:");

        jLabel8.setText("iterations:");

        OneMax_Name.setText("OneMax");
        OneMax_Name.setEnabled(false);

        OneMax_ProblemID.setText("1");

        OneMax_Population.setText("1000");

        OneMax_Alello.setText("100");

        OneMax_BestFitness.setText("90");

        OneMax_Iteracoes.setText("1000");

        jLabel9.setText("OneMax Generator");

        jLabel10.setText("ClientID:");

        OneMax_ClientID.setText("1");

        OneMax_Carregar.setText("Gerar");
        OneMax_Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneMax_CarregarActionPerformed(evt);
            }
        });

        jLabel25.setText("selection");

        Text_SelectionValor.setText("70");

        ComboBox_Selection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "roulette", "sus", "tournament" }));
        ComboBox_Selection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBox_SelectionItemStateChanged(evt);
            }
        });
        ComboBox_Selection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_SelectionActionPerformed(evt);
            }
        });

        jLabel26.setText("Valor:");

        jLabel27.setText("mutation");

        ComboBox_mutation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "flipbit" }));

        jLabel28.setText("Valor:");

        Text_MutationValor.setText("0.01");

        jLabel30.setText("recombination");

        ComboBox_recombination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "crossover", "uniformcrossover" }));

        jLabel31.setText("replacement");

        ComboBox_replacement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "tournament", "truncation" }));

        Text_Recombination_1.setText("1000");

        jLabel32.setText("Valor1:");

        jLabel33.setText("Valor2:");

        Text_Recombination_2.setText("2");

        Text_SelectionValor_2.setEditable(false);
        Text_SelectionValor_2.setText("100");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(354, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(360, 360, 360))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OneMax_Population, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(OneMax_Alello, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(OneMax_BestFitness, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(OneMax_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(OneMax_Iteracoes, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(OneMax_ClientID, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(OneMax_ProblemID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel25))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(ComboBox_replacement, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                                .addComponent(jLabel32))
                                            .addComponent(ComboBox_recombination, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Text_Recombination_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBox_Selection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBox_mutation, 0, 88, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel26)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Text_SelectionValor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel28))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Text_MutationValor)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Text_SelectionValor_2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_Recombination_2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(371, 371, 371))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(426, Short.MAX_VALUE)
                .addComponent(OneMax_Carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(OneMax_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(OneMax_ProblemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(OneMax_ClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(OneMax_Population, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(OneMax_Alello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_recombination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBox_Selection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26)
                                    .addComponent(Text_SelectionValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_SelectionValor_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel25)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel27)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(ComboBox_mutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_MutationValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(OneMax_BestFitness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OneMax_Iteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBox_replacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Recombination_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)
                            .addComponent(Text_Recombination_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addComponent(OneMax_Carregar)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        TabMain.addTab("OneMax", jPanel2);

        jLabel11.setText("KnapSack Generator");

        jLabel12.setText("Problem Name:");

        KnapSack_Name.setText("KnapSack");
        KnapSack_Name.setEnabled(false);

        jLabel13.setText("ProblemID:");

        KnapSack_ProblemID.setText("1");
        KnapSack_ProblemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnapSack_ProblemIDActionPerformed(evt);
            }
        });

        jLabel14.setText("ClientID:");

        KnapSack_ClientID.setText("1");

        jLabel15.setText("Population size:");

        KnapSack_Population.setText("1000");

        jLabel17.setText("Param Best fitness:");

        KnapSack_BestFitness.setText("1921");

        jLabel18.setText("iterations:");

        KnapSack_Iteracoes.setText("10000");

        KnapSack_Gerar.setText("Gerar");
        KnapSack_Gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnapSack_GerarActionPerformed(evt);
            }
        });

        jLabel16.setText("MAX_WEIGHT:");

        KnapSack_NumItems.setText("Allelo:");

        KnapSack_Penalty.setText("PARAM_PENALTY:");

        KnapSack_MaxWeight.setText("1473");

        KnapSack_Allelo.setText("50");
        KnapSack_Allelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnapSack_AlleloActionPerformed(evt);
            }
        });

        KnapSack_PenaltY.setText("2");
        KnapSack_PenaltY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnapSack_PenaltYActionPerformed(evt);
            }
        });

        jLabel19.setText("Adicionar Itens");

        jLabel20.setText("Peso:");

        KnapSack_Peso.setText("10");

        jLabel23.setText("Valor:");

        KnapSack_Valor.setText("5");

        KnapSack_Monitor.setColumns(20);
        KnapSack_Monitor.setRows(5);
        jScrollPane2.setViewportView(KnapSack_Monitor);

        KnapSack_Adicionar.setText("Adicionar");
        KnapSack_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KnapSack_AdicionarActionPerformed(evt);
            }
        });

        ComboBox_Selection_KnapSack.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "roulette", "sus", "tournament" }));
        ComboBox_Selection_KnapSack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_Selection_KnapSackActionPerformed(evt);
            }
        });

        ComboBox_Mutation_KnapSack.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "flipbit" }));

        ComboBox_Recombination_KnapSack.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "crossover", "uniformcrossover" }));

        jLabel34.setText("selection");

        jLabel35.setText("mutation");

        jLabel36.setText("recombination");

        jLabel37.setText("replacement");

        jLabel38.setText("Valor:");

        jLabel39.setText("Valor:");

        jLabel40.setText("Valor1:");

        Text_Replacement_1.setText("1000");

        jLabel41.setText("Valor2:");

        Text_Replacement_2.setText("2");

        ComboBox_replacement_KnapSack.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "tournament", "truncation" }));

        jLabel42.setText("Lista de Itens");

        Text_Mutation_KnapSack.setText("0.01");

        Text_SelectionValor_KnapSack.setText("100");

        jLabel21.setText("Mode(1,2,3):");

        jLabel22.setText("Lenght:");

        KnapSack_Mode.setText("1");

        Text_SelectionValor_KnapSack2.setEditable(false);
        Text_SelectionValor_KnapSack2.setText("100");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(KnapSack_NumItems)
                            .addComponent(KnapSack_Penalty)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(KnapSack_MaxWeight)
                                .addComponent(KnapSack_Name)
                                .addComponent(KnapSack_Iteracoes)
                                .addComponent(KnapSack_BestFitness)
                                .addComponent(KnapSack_Population)
                                .addComponent(KnapSack_ClientID, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(KnapSack_ProblemID))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(KnapSack_Lenght, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(KnapSack_PenaltY, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(KnapSack_Mode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(KnapSack_Allelo, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel34)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel38))
                                            .addComponent(jLabel35)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel39)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Text_SelectionValor_KnapSack, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Text_Mutation_KnapSack, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ComboBox_Selection_KnapSack, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBox_Mutation_KnapSack, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBox_Recombination_KnapSack, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ComboBox_replacement_KnapSack, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(KnapSack_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(KnapSack_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel40)
                                            .addComponent(jLabel41))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Text_Replacement_2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                            .addComponent(Text_Replacement_1)))
                                    .addComponent(jLabel19))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_SelectionValor_KnapSack2)
                            .addComponent(KnapSack_Adicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(281, Short.MAX_VALUE)
                        .addComponent(KnapSack_Gerar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel42)))
                .addGap(76, 76, 76))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(KnapSack_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel34))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(KnapSack_ProblemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(KnapSack_ClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel15)
                                            .addComponent(KnapSack_Population, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel17)
                                            .addComponent(KnapSack_BestFitness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel36))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBox_Selection_KnapSack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_SelectionValor_KnapSack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38)
                                    .addComponent(Text_SelectionValor_KnapSack2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBox_Mutation_KnapSack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Text_Mutation_KnapSack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39))
                                .addGap(33, 33, 33)
                                .addComponent(ComboBox_Recombination_KnapSack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(KnapSack_Iteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(KnapSack_MaxWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(KnapSack_NumItems)
                                    .addComponent(KnapSack_Allelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel40)
                                    .addComponent(Text_Replacement_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBox_replacement_KnapSack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel41)
                                    .addComponent(Text_Replacement_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(KnapSack_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KnapSack_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(KnapSack_Adicionar))
                                .addGap(18, 18, 18)
                                .addComponent(KnapSack_Gerar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(KnapSack_Mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(KnapSack_Lenght, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(KnapSack_Penalty)
                                    .addComponent(KnapSack_PenaltY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)))
                .addContainerGap())
        );

        TabMain.addTab("KnapSack", jPanel3);

        ProblemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Exemplo1", "Exemplo2", "Exemplo3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ProblemList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProblemListMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ProblemList);

        jLabel24.setText("Problems");

        jTextField1.setText("100");

        jTextField2.setText("100");

        jLabel43.setText("Pop.Size:");

        jLabel44.setText("Parameters:");

        txtProblem.setColumns(20);
        txtProblem.setEditable(false);
        txtProblem.setRows(5);
        jScrollPane4.setViewportView(txtProblem);

        jLabel45.setText("Info");

        jButton1.setText("Set Parameters");

        jButton2.setText("Create Population");

        jTextField3.setEditable(false);
        jTextField3.setText("Exemplo 1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addGap(257, 257, 257))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        TabMain.addTab("Problem", jPanel4);

        SelectionList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Exemplo1", "Exemplo2", "Exemplo3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        SelectionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SelectionListMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(SelectionList);

        txtSelection.setColumns(20);
        txtSelection.setEditable(false);
        txtSelection.setRows(5);
        jScrollPane9.setViewportView(txtSelection);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                        .addGap(31, 31, 31))))
        );

        TabMain.addTab("Selection", jPanel5);

        RecombinationList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Exemplo1", "Exemplo2", "Exemplo3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        RecombinationList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecombinationListMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(RecombinationList);

        txtRecombination.setColumns(20);
        txtRecombination.setEditable(false);
        txtRecombination.setRows(5);
        jScrollPane10.setViewportView(txtRecombination);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                        .addGap(39, 39, 39))))
        );

        TabMain.addTab("Recombination", jPanel6);

        MutationList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Exemplo1", "Exemplo2", "Exemplo3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        MutationList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MutationListMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(MutationList);

        txtMutation.setColumns(20);
        txtMutation.setEditable(false);
        txtMutation.setRows(5);
        jScrollPane11.setViewportView(txtMutation);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                        .addGap(39, 39, 39))))
        );

        TabMain.addTab("Mutation", jPanel7);

        ReplacementList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Exemplo1", "Exemplo2", "Exemplo3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ReplacementList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReplacementListMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(ReplacementList);

        txtReplacement.setColumns(20);
        txtReplacement.setEditable(false);
        txtReplacement.setRows(5);
        jScrollPane12.setViewportView(txtReplacement);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                        .addGap(39, 39, 39))))
        );

        TabMain.addTab("Replacement", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadData(JList campo,ArrayList<String> data){
        DefaultListModel dados = new DefaultListModel();
        campo.setModel(dados);
        dados.removeAllElements();
        for (int i = 0; i < data.size(); i++) {
            dados.add(i, data.get(i));
        }
    }
    
private void ComboBox_Selection_KnapSackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_Selection_KnapSackActionPerformed
    if(ComboBox_Selection_KnapSack.getSelectedItem()=="tournament"){
           Text_SelectionValor_KnapSack2.setEditable(true);
    }else{
           Text_SelectionValor_KnapSack2.setEditable(false);
    }
}//GEN-LAST:event_ComboBox_Selection_KnapSackActionPerformed

private void KnapSack_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnapSack_AdicionarActionPerformed
        //peso.add(KnapSack_Peso.getText());
        //valor.add(KnapSack_Valor.getText());
        String peso=KnapSack_Peso.getText();
        String valor=KnapSack_Valor.getText();
        KnapSack_Monitor.append(peso+","+valor+"\n");
        String texto_monitor = KnapSack_Monitor.getText();
        String[] linhas = texto_monitor.split("\n");
        KnapSack_Lenght.setText(String.valueOf(linhas.length));
}//GEN-LAST:event_KnapSack_AdicionarActionPerformed

private void KnapSack_PenaltYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnapSack_PenaltYActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_KnapSack_PenaltYActionPerformed

private void KnapSack_AlleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnapSack_AlleloActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_KnapSack_AlleloActionPerformed

private void KnapSack_GerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnapSack_GerarActionPerformed
    try{
        URLSite=false;
        TextArea.setText("");
        String PrimeiraLinha;
        String nome=KnapSack_Name.getText();
        String KnapSackProblemID=KnapSack_ProblemID.getText();
        String KnapSackClientID=KnapSack_ClientID.getText();
        String PARAM_ITERATIONS=KnapSack_Iteracoes.getText();
        String PARAM_POPULATION_SIZE=KnapSack_Population.getText();
        String PARAM_BEST_FITNESS=KnapSack_BestFitness.getText();
        String Mode=KnapSack_Mode.getText();
        String lenght=KnapSack_Lenght.getText();
        String KnapSack_allelo=KnapSack_Allelo.getText();
        String PARAM_PENALTY=KnapSack_PenaltY.getText();
        
        if(VerInt(KnapSackProblemID) &&VerInt(KnapSackClientID) &&VerInt(PARAM_ITERATIONS) &&VerInt(PARAM_POPULATION_SIZE) &&VerInt(PARAM_BEST_FITNESS) &&VerInt(PARAM_PENALTY) &&VerInt(Mode)){
        //METER ITENS NO ARRAY
       
        String texto_monitor = KnapSack_Monitor.getText();
        //DA-TE AS LINHAS TODAS
        String[] linhas = texto_monitor.split("\n");
        String itens="";
        KnapSack_Lenght.setText(String.valueOf(linhas.length));
            for (int i = 0; i < linhas.length; i++) {
                itens+="["+linhas[i]+"]";
                if(i!=linhas.length-1)
                itens+=",";
            }  

        
         if(ComboBox_Selection_KnapSack.getSelectedItem()=="tournament"){    
           PrimeiraLinha = "{type:"+nome+",id:"+KnapSackProblemID+",client:"+KnapSackClientID+",selection:["+ComboBox_Selection_KnapSack.getSelectedItem()+","+Text_SelectionValor_KnapSack.getText()+","+Text_SelectionValor_KnapSack2.getText()+"],mutation:["+ComboBox_Mutation_KnapSack.getSelectedItem()+","+Text_Mutation_KnapSack.getText()+"],recombination:["+ComboBox_Recombination_KnapSack.getSelectedItem()+"],replacement:["+ComboBox_replacement_KnapSack.getSelectedItem()+","+Text_Replacement_1.getText()+","+Text_Replacement_2.getText()+"],iterations:"+PARAM_ITERATIONS+",pop:"+PARAM_POPULATION_SIZE+",alello:"+KnapSack_allelo+",best:"+PARAM_BEST_FITNESS+",penalty:"+PARAM_PENALTY+",mode:"+Mode+",weight:"+KnapSack_MaxWeight.getText()+",lenght:"+lenght+",data:["+itens+"]}";
         }else if(ComboBox_replacement.getSelectedItem()=="truncation"){
         PrimeiraLinha = "{type:"+nome+",id:"+KnapSack_ProblemID.getText()+",client:"+KnapSack_ClientID.getText()+",selection:["+ComboBox_Selection_KnapSack.getSelectedItem()+","+Text_SelectionValor_KnapSack.getText()+"],mutation:["+ComboBox_Mutation_KnapSack.getSelectedItem()+","+Text_Mutation_KnapSack.getText()+"],recombination:["+ComboBox_Recombination_KnapSack.getSelectedItem()+"],replacement:["+ComboBox_replacement_KnapSack.getSelectedItem()+","+Text_Replacement_1.getText()+"],iterations:"+PARAM_ITERATIONS+",pop:"+PARAM_POPULATION_SIZE+",alello:"+KnapSack_allelo+",best:"+PARAM_BEST_FITNESS+",penalty:"+PARAM_PENALTY+",mode:"+Mode+",weight:"+KnapSack_MaxWeight.getText()+",lenght:"+KnapSack_Lenght.getText()+",data:["+itens+"]}";    
         }else{
           PrimeiraLinha = "{type:"+nome+",id:"+KnapSack_ProblemID.getText()+",client:"+KnapSack_ClientID.getText()+",selection:["+ComboBox_Selection_KnapSack.getSelectedItem()+","+Text_SelectionValor_KnapSack.getText()+"],mutation:["+ComboBox_Mutation_KnapSack.getSelectedItem()+","+Text_Mutation_KnapSack.getText()+"],recombination:["+ComboBox_Recombination_KnapSack.getSelectedItem()+"],replacement:["+ComboBox_replacement_KnapSack.getSelectedItem()+","+Text_Replacement_1.getText()+","+Text_Replacement_2.getText()+"],iterations:"+PARAM_ITERATIONS+",pop:"+PARAM_POPULATION_SIZE+",alello:"+KnapSack_allelo+",best:"+PARAM_BEST_FITNESS+",penalty:"+PARAM_PENALTY+",mode:"+Mode+",weight:"+KnapSack_MaxWeight.getText()+",lenght:"+KnapSack_Lenght.getText()+",data:["+itens+"]}";    
         }

    //KnapSack_MaxWeight;
         //PrimeiraLinha+="]}";
         String NameFile="KnapSack.pc";
            
            TextArea.append(PrimeiraLinha+"\n\n");
            TextArea.append("//////////////PARAMETROS KNAPSACK///////////"+"\n\n");
            TextArea.append("Nome: "+nome+"\n");
            TextArea.append("ProblemID: "+KnapSackProblemID+"\n");
            TextArea.append("ClientID: "+KnapSackClientID+"\n");
            TextArea.append("Iteration: "+PARAM_ITERATIONS+"\n");
            TextArea.append("Population: "+PARAM_POPULATION_SIZE+"\n");
            TextArea.append("Best: "+PARAM_BEST_FITNESS+"\n");
            TextArea.append("Mode: "+Mode+"\n");
            TextArea.append("Lenght: "+lenght+"\n");
            TextArea.append("Allelo: "+KnapSack_allelo+"\n");
            TextArea.append("Penalty: "+PARAM_PENALTY+"\n");
         
         FileWriter testFile = new FileWriter(NameFile);
         File file = new File(NameFile);
         BufferedWriter output = new BufferedWriter(testFile);
         output.write(PrimeiraLinha);
         output.close();
         System.out.println("Your file has been written");
         //KnapSack_Monitor.setText("");
         caminho=file.getAbsolutePath().toString();
         Text_Caminho.setText("File:"+caminho);

               Carregar.setEnabled(true);
               Executar.setEnabled(true);
        
         
          
          
          
        }else{
         TextArea.setText("\nErro ao carregar o knapSack, parametros invalidos");
        }  
        TabMain.setSelectedIndex(0);
    }catch(Exception e){
         TextArea.setText("\nErro ao carregar KnapSack "+e);
         KnapSack_Monitor.setText("");
         Executar.setEnabled(false);
    }
 
}//GEN-LAST:event_KnapSack_GerarActionPerformed

private void KnapSack_ProblemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KnapSack_ProblemIDActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_KnapSack_ProblemIDActionPerformed

private void ComboBox_SelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_SelectionActionPerformed
    if(ComboBox_Selection.getSelectedItem()=="tournament"){
           Text_SelectionValor_2.setEditable(true);
    }else{
           Text_SelectionValor_2.setEditable(false);
    }
}//GEN-LAST:event_ComboBox_SelectionActionPerformed

private void ComboBox_SelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBox_SelectionItemStateChanged

}//GEN-LAST:event_ComboBox_SelectionItemStateChanged

private void OneMax_CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneMax_CarregarActionPerformed
   try{
        URLSite=false;
        TextArea.setText("");
        String PrimeiraLinha;
        String nome=OneMax_Name.getText();
        String OneMaxProblemID=OneMax_ProblemID.getText();
        String OneMaxClientID=OneMax_ClientID.getText();
        String OneMaxPopulation=OneMax_Population.getText();
        String OneMaxAlello=OneMax_Alello.getText();
        String OneMaxBestFitness=OneMax_BestFitness.getText();
        String OneMaxIteracoes=OneMax_Iteracoes.getText();
        if(VerInt(OneMaxProblemID) &&VerInt(OneMaxClientID) &&VerInt(OneMaxPopulation) &&VerInt(OneMaxAlello) &&VerInt(OneMaxBestFitness) &&VerInt(OneMaxIteracoes)){
        
            String NameFile="OneMax.pc";
            if(ComboBox_Selection.getSelectedItem()=="tournament"){
                PrimeiraLinha = "{type:\""+nome+"\",id:"+OneMaxProblemID+",client:"+OneMaxClientID+",selection:[\""+ComboBox_Selection.getSelectedItem()+"\","+Text_SelectionValor.getText()+","+Text_SelectionValor_2.getText()+"],mutation:[\""+ComboBox_mutation.getSelectedItem()+"\","+Text_MutationValor.getText()+"],recombination:[\""+ComboBox_recombination.getSelectedItem()+"\"],replacement:[\""+ComboBox_replacement.getSelectedItem()+"\","+Text_Recombination_1.getText()+","+Text_Recombination_2.getText()+"],iterations:"+OneMaxIteracoes+",pop:"+OneMaxPopulation+",alello:"+OneMaxAlello+",best:"+OneMaxBestFitness+",lenght:1000,data:[[x,y],[y,z],[b,a]]}";
            }else if(ComboBox_replacement.getSelectedItem()=="truncation"){
                PrimeiraLinha = "{type:"+nome+",id:"+OneMaxProblemID+",client:"+OneMaxClientID+",selection:["+ComboBox_Selection.getSelectedItem()+","+Text_SelectionValor.getText()+"],mutation:["+ComboBox_mutation.getSelectedItem()+","+Text_MutationValor.getText()+"],recombination:["+ComboBox_recombination.getSelectedItem()+"],replacement:["+ComboBox_replacement.getSelectedItem()+","+Text_Recombination_1.getText()+"],iterations:"+OneMaxIteracoes+",pop:"+OneMaxPopulation+",alello:"+OneMaxAlello+",best:"+OneMaxBestFitness+",lenght:1000,data:[[x,y],[y,z],[b,a]]}";    
            }else{
                PrimeiraLinha = "{type:"+nome+",id:"+OneMaxProblemID+",client:"+OneMaxClientID+",selection:["+ComboBox_Selection.getSelectedItem()+","+Text_SelectionValor.getText()+"],mutation:["+ComboBox_mutation.getSelectedItem()+","+Text_MutationValor.getText()+"],recombination:["+ComboBox_recombination.getSelectedItem()+"],replacement:["+ComboBox_replacement.getSelectedItem()+","+Text_Recombination_1.getText()+","+Text_Recombination_2.getText()+"],iterations:"+OneMaxIteracoes+",pop:"+OneMaxPopulation+",alello:"+OneMaxAlello+",best:"+OneMaxBestFitness+",lenght:1000,data:[[x,y],[y,z],[b,a]]}";
            }
            
            
            TextArea.append(PrimeiraLinha+"\n\n");
            TextArea.append("//////////////PARAMETROS ONEMAX///////////"+"\n\n");
            TextArea.append("Nome: "+nome+"\n");
            TextArea.append("ProblemID: "+OneMaxProblemID+"\n");
            TextArea.append("ClientID: "+OneMaxClientID+"\n");
            TextArea.append("Iteration: "+OneMaxIteracoes+"\n");
            TextArea.append("Population: "+OneMaxPopulation+"\n");
            TextArea.append("Best: "+OneMaxBestFitness+"\n");
            TextArea.append("Allelo: "+OneMaxAlello+"\n");

            
            FileWriter testFile = new FileWriter(NameFile);
            File file = new File(NameFile);
            BufferedWriter output = new BufferedWriter(testFile);
            output.write(PrimeiraLinha);
            output.close();
            System.out.println("Your file has been written");
            
            caminho=file.getAbsolutePath().toString();
            Text_Caminho.setText("File:"+caminho);
            
               Carregar.setEnabled(true);
               Executar.setEnabled(true);
            
            
         }else{
            TextArea.setText("\nErro ao carregar o OneMax, parametros invalidos");
            }     
         TabMain.setSelectedIndex(0);   
   }catch(Exception e){
       TextArea.setText("\nErro ao carregar OneMax "+e);
       Executar.setEnabled(false);
   }
   
}//GEN-LAST:event_OneMax_CarregarActionPerformed

private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
    TextArea.setText("");
}//GEN-LAST:event_LimparActionPerformed

private void ExecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExecutarActionPerformed
  
            //Verificação se está tudo Ok
        if (URLSite) {
             Executar.setEnabled(true);
             Emulador.IniciarPeloEmulador(caminho);
             //TextArea.append("\n\nPROBLEMA FINALIZADO");
             Carregar.setEnabled(true);
        }else{
             Executar.setEnabled(true);
             Emulador.IniciarPeloEmulador("File:"+caminho);
             //TextArea.append("\n\nPROBLEMA FINALIZADO");
             Carregar.setEnabled(true);
        }
   
    
}//GEN-LAST:event_ExecutarActionPerformed

private void CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarActionPerformed
   URLSite=true;
   TextArea.setText("");
   EmuladorEcran.TextArea.append("\nA Carregar dados...\n");
   caminho=Text_Caminho.getText();
  
    
       Carregar.setEnabled(true);
       Executar.setEnabled(true);
    
}//GEN-LAST:event_CarregarActionPerformed

private void Text_CaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_CaminhoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_Text_CaminhoActionPerformed

private void ModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModulosActionPerformed
    //Aplication app = new Aplication();
  
    Modulos.setEnabled(false);
    Executar.setEnabled(true);
    Carregar.setEnabled(true);
    OneMax_Carregar.setEnabled(true);
    KnapSack_Gerar.setEnabled(true);
}//GEN-LAST:event_ModulosActionPerformed

    private void ProblemListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProblemListMouseClicked
       
        ListModel lm = this.ProblemList.getModel();
        String selected = (String)lm.getElementAt(this.ProblemList.getSelectedIndex());
        this.txtProblem.setText(this.loader.getConstructors(selected));
        
        
        
    }//GEN-LAST:event_ProblemListMouseClicked

    private void SelectionListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SelectionListMouseClicked
        ListModel lm = this.SelectionList.getModel();
        String selected = (String)lm.getElementAt(this.SelectionList.getSelectedIndex());
        this.txtSelection.setText(this.loader.getConstructors(selected));
    }//GEN-LAST:event_SelectionListMouseClicked

    private void RecombinationListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecombinationListMouseClicked
        ListModel lm = this.RecombinationList.getModel();
        String selected = (String)lm.getElementAt(this.RecombinationList.getSelectedIndex());
        this.txtRecombination.setText(this.loader.getConstructors(selected));
    }//GEN-LAST:event_RecombinationListMouseClicked

    private void MutationListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MutationListMouseClicked
         ListModel lm = this.MutationList.getModel();
        String selected = (String)lm.getElementAt(this.MutationList.getSelectedIndex());
        this.txtMutation.setText(this.loader.getConstructors(selected));
    }//GEN-LAST:event_MutationListMouseClicked

    private void ReplacementListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReplacementListMouseClicked
         ListModel lm = this.ReplacementList.getModel();
        String selected = (String)lm.getElementAt(this.ReplacementList.getSelectedIndex());
        this.txtReplacement.setText(this.loader.getConstructors(selected));
    }//GEN-LAST:event_ReplacementListMouseClicked

    public Boolean VerInt(String valor){
        boolean bem=false;
        try{
            Integer.parseInt(valor);
            bem=true;
        }catch(Exception e){
            return false;
        }
        return bem;
    }
    
    public Boolean VerString(String texto){
        boolean bem=false;
        try{
            bem=true;
        }catch(Exception e){
            return false;
        }
        return bem;
    }

    public static void Escrever(String msg){
        EmuladorEcran.TextArea.append("\n"+msg);
    }
    public static void LimparEcran(){
        EmuladorEcran.TextArea.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmuladorEcran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmuladorEcran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmuladorEcran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmuladorEcran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new EmuladorEcran().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carregar;
    private javax.swing.JComboBox ComboBox_Mutation_KnapSack;
    private javax.swing.JComboBox ComboBox_Recombination_KnapSack;
    public static javax.swing.JComboBox ComboBox_Selection;
    private javax.swing.JComboBox ComboBox_Selection_KnapSack;
    private javax.swing.JComboBox ComboBox_mutation;
    private javax.swing.JComboBox ComboBox_recombination;
    private javax.swing.JComboBox ComboBox_replacement;
    private javax.swing.JComboBox ComboBox_replacement_KnapSack;
    private javax.swing.JButton Executar;
    private javax.swing.JButton KnapSack_Adicionar;
    private javax.swing.JTextField KnapSack_Allelo;
    private javax.swing.JTextField KnapSack_BestFitness;
    private javax.swing.JTextField KnapSack_ClientID;
    private javax.swing.JButton KnapSack_Gerar;
    private javax.swing.JTextField KnapSack_Iteracoes;
    private javax.swing.JTextField KnapSack_Lenght;
    private javax.swing.JTextField KnapSack_MaxWeight;
    private javax.swing.JTextField KnapSack_Mode;
    private javax.swing.JTextArea KnapSack_Monitor;
    private javax.swing.JTextField KnapSack_Name;
    private javax.swing.JLabel KnapSack_NumItems;
    private javax.swing.JTextField KnapSack_PenaltY;
    private javax.swing.JLabel KnapSack_Penalty;
    private javax.swing.JTextField KnapSack_Peso;
    private javax.swing.JTextField KnapSack_Population;
    private javax.swing.JTextField KnapSack_ProblemID;
    private javax.swing.JTextField KnapSack_Valor;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton Modulos;
    private javax.swing.JList MutationList;
    private javax.swing.JTextField OneMax_Alello;
    private javax.swing.JTextField OneMax_BestFitness;
    private javax.swing.JButton OneMax_Carregar;
    private javax.swing.JTextField OneMax_ClientID;
    private javax.swing.JTextField OneMax_Iteracoes;
    private javax.swing.JTextField OneMax_Name;
    private javax.swing.JTextField OneMax_Population;
    private javax.swing.JTextField OneMax_ProblemID;
    private javax.swing.JList ProblemList;
    private javax.swing.JList RecombinationList;
    private javax.swing.JList ReplacementList;
    private javax.swing.JList SelectionList;
    private javax.swing.JTabbedPane TabMain;
    public static javax.swing.JTextArea TextArea;
    private javax.swing.JTextField Text_Caminho;
    private javax.swing.JTextField Text_MutationValor;
    private javax.swing.JTextField Text_Mutation_KnapSack;
    private javax.swing.JTextField Text_Recombination_1;
    private javax.swing.JTextField Text_Recombination_2;
    private javax.swing.JTextField Text_Replacement_1;
    private javax.swing.JTextField Text_Replacement_2;
    private javax.swing.JTextField Text_SelectionValor;
    private javax.swing.JTextField Text_SelectionValor_2;
    private javax.swing.JTextField Text_SelectionValor_KnapSack;
    private javax.swing.JTextField Text_SelectionValor_KnapSack2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextArea txtMutation;
    private javax.swing.JTextArea txtProblem;
    private javax.swing.JTextArea txtRecombination;
    private javax.swing.JTextArea txtReplacement;
    private javax.swing.JTextArea txtSelection;
    // End of variables declaration//GEN-END:variables
}
